config/routes.rb
get 'projects/:id/issues/average_age_report', :to => 'project_reports#average_age_report', :as => 'project_issues_average_age_report'
get 'projects/:id/issues/created_vs_resolved_report', :to => 'project_reports#created_vs_resolved_report', :as => 'project_issues_created_vs_resolved_report'
get 'projects/:id/issues/pie_chart_report', :to => 'project_reports#pie_chart_report', :as => 'project_issues_pie_chart_report'
get 'projects/:id/issues/status_time_report', :to => 'project_reports#status_time_report', :as => 'status_time_report'
get 'projects/:id/issues/all_projects_closed_vs_resolved_report', :to => 'project_reports#all_projects_closed_vs_resolved_report', :as => 'project_issues_all_projects_closed_vs_resolved_report'

app/views/shared/_average_age_diagram.erb
<%= stylesheet_link_tag 'style', :plugin => 'redmine_report_filters' %>
<%= javascript_include_tag 'amcharts.js', :plugin => 'redmine_report_filters' %>
<%= javascript_include_tag 'serial.js', :plugin => 'redmine_report_filters' %>

<script type="text/javascript">
    var chart;

    var chartData = [
        <%= @chart.html_safe %>
    ];


    AmCharts.ready(function () {
        // SERIAL CHART
        chart = new AmCharts.AmSerialChart();
        chart.dataProvider = chartData;
        chart.categoryField = "date";
        chart.startDuration = 1;

        // AXES
        // category
        var categoryAxis = chart.categoryAxis;
        categoryAxis.labelRotation = 45; // this line makes category values to be rotated
        categoryAxis.gridAlpha = 0;
        categoryAxis.fillAlpha = 1;
        categoryAxis.fillColor = "#FAFAFA";
        categoryAxis.gridPosition = "start";

        // value
        var valueAxis = new AmCharts.ValueAxis();
        valueAxis.dashLength = 5;
        valueAxis.title = "<%= t(:days) %>";
        valueAxis.axisAlpha = 0;
        chart.addValueAxis(valueAxis);

        // GRAPH
        var graph = new AmCharts.AmGraph();
        graph.valueField = "days";
        graph.colorField = "color";
        graph.balloonText = "<b>[[category]]: [[value]]</b>";
        graph.type = "column";
        graph.lineAlpha = 0;
        graph.fillAlphas = 1;
        chart.addGraph(graph);

        // CURSOR
        var chartCursor = new AmCharts.ChartCursor();
        chartCursor.cursorAlpha = 0;
        chartCursor.zoomable = false;
        chartCursor.categoryBalloonEnabled = false;
        chart.addChartCursor(chartCursor);

        chart.creditsPosition = "top-right";

        // WRITE
        chart.write("chartdiv");
    });
</script>
</head>

<body>
<div id="chartdiv" style="width: 100%; height: 600px;"></div>
<br><br>
<% if @table_results.present? %>
    <div class="CSSTableGenerator" >
      <table >
        <tr>
          <td>
            <%= t(:period) %>
          </td>
          <td >
            <%= t(:issues_unresolved) %>
          </td>
          <td >
            <%= t(:total_age) %>
          </td>
          <td >
            <%= t(:avg_age) %>
          </td>
        </tr>
        <% @table_results.each do |t| %>
            <tr>
              <td>
                <%= t.period %>
              </td>
              <td >
                <%= t.unresolved %>
              </td>
              <td >
                <%= t.total_age %>
              </td>
              <td >
                <%= t.avg_age %>
              </td>
            </tr>
        <% end %>
      </table>
    </div>
<% end %>

</body>

app/views/shared/_created_vs_resolved_issues_report_diagram.erb
<%= stylesheet_link_tag 'style', :plugin => 'redmine_report_filters' %>
<%= javascript_include_tag 'amcharts.js', :plugin => 'redmine_report_filters' %>
<%= javascript_include_tag 'serial.js', :plugin => 'redmine_report_filters' %>
<script type="text/javascript">

    // since v3, chart can accept data in JSON format
    // if your category axis parses dates, you should only
    // set date format of your data (dataDateFormat property of AmSerialChart)
    var chartData = [<%= @chart.html_safe %>
    ];
    var chart;

    AmCharts.ready(function () {
        // SERIAL CHART
        chart = new AmCharts.AmSerialChart();
        chart.dataProvider = chartData;
        chart.pathToImages = "../amcharts/images/";
        chart.categoryField = "date";
        chart.dataDateFormat = "YYYY-MM-DD";

        var balloon = chart.balloon;
        balloon.cornerRadius = 6;
        balloon.adjustBorderColor = false;
        balloon.horizontalPadding = 10;
        balloon.verticalPadding = 10;

        // AXES
        // category axis
        var categoryAxis = chart.categoryAxis;
        categoryAxis.labelRotation = 45; // this line makes category values to be rotated
        categoryAxis.parseDates = false; // as our data is date-based, we set parseDates to true
        categoryAxis.autoGridCount = false;
        categoryAxis.gridCount = 50;
        categoryAxis.gridAlpha = 0;
        categoryAxis.gridColor = "#000000";
        categoryAxis.axisColor = "#555555";

        // as we have data of different units, we create two different value axes
        // Duration value axis
        var durationAxis = new AmCharts.ValueAxis();
        durationAxis.gridAlpha = 0.05;
        durationAxis.axisAlpha = 0;
        chart.addValueAxis(durationAxis);


        // GRAPHS
        // duration graph
        var createdGraph = new AmCharts.AmGraph();
        createdGraph.title = "<%= t(:created) %>";
        createdGraph.valueField = "created";
        createdGraph.type = "line";
        createdGraph.valueAxis = durationAxis; // indicate which axis should be used
        createdGraph.lineColorField = "createdColor";
        createdGraph.fillColorsField = "createdColor";
        createdGraph.fillAlphas = 0.3;
        createdGraph.balloonText = "<%= t(:created) %> : [[value]]";
        createdGraph.lineThickness = 1;
        createdGraph.balloonColor = "#FF3030";
        createdGraph.legendValueText = "[[value]]";
        createdGraph.bullet = "square";
        createdGraph.bulletBorderThickness = 1;
        createdGraph.bulletBorderAlpha = 1;
        chart.addGraph(createdGraph);

        var resolvedGraph = new AmCharts.AmGraph();
        resolvedGraph.title = "<%= t(:resolved) %>";
        resolvedGraph.valueField = "resolved";
        resolvedGraph.type = "line";
        resolvedGraph.valueAxis = durationAxis; // indicate which axis should be used
        resolvedGraph.lineColorField = "resolvedColor";
        resolvedGraph.fillColorsField = "resolvedColor";
        resolvedGraph.fillAlphas = 0.3;
        resolvedGraph.balloonText = "<%= t(:resolved) %> : [[value]]";
        resolvedGraph.balloonColor = "#009900";
        resolvedGraph.lineThickness = 1;
        resolvedGraph.legendValueText = "[[value]]";
        resolvedGraph.bullet = "square";
        resolvedGraph.bulletBorderThickness = 1;
        resolvedGraph.bulletBorderAlpha = 1;
        chart.addGraph(resolvedGraph);
        // CURSOR
        var chartCursor = new AmCharts.ChartCursor();
        chartCursor.zoomable = false;
        chartCursor.categoryBalloonDateFormat = "YYYY MMM DD";
        chartCursor.cursorAlpha = 0;
        chart.addChartCursor(chartCursor);

        // WRITE
        chart.write("chartdiv");
    });
</script>

<br>
<br>
<div id="chartdiv" style="width:100%; height:600px;"></div>
<br><br>
<% if @table_results.present? %>
    <div class="CSSTableGenerator" >
      <table >
        <tr>
          <td>
            <%= t(:period) %>
          </td>
          <td >
            <%= t(:created) %>
          </td>
          <td >
            <%= t(:resolved) %>
          </td>
        </tr>
        <% @table_results.each do |t| %>
            <tr>
              <td>
                <%= t.period %>
              </td>
              <td >
                <%= t.unresolved %>
              </td>
              <td >
                <%= t.total_age %>
              </td>
            </tr>
        <% end %>
      </table>
    </div>
<% end %>

app/views/shared/_filters.erb
<%= form_tag({ :controller => 'reports', :action => 'issue_report', :project_id => @project },
             :method => :get, :id => 'query_form') do %>
    <div id="query_form_with_buttons" class="hide-when-print">
      <%= hidden_field_tag 'set_filter', '1' %>
      <div id="query_form_content">
        <fieldset id="filters" class="collapsible <%= @query.new_record? ? "" : "collapsed" %>">
          <legend onclick="toggleFieldset(this);"><%= l(:label_filter_plural) %></legend>
          <div style="<%= @query.new_record? ? "" : "display: none;" %>">
            <%= render :partial => 'queries/filters', :locals => {:query => @query} %>
            <table>
              <tr class="filter" id="tr_dates">
                <td class="field"><input id="cb_dates" name="cb_dates" value="true" type="checkbox" onchange="$(this).val($(this).prop('checked'));" <%= session[:cb_dates] %>><label for="cb_dates"> <%= t(:report_data) %></label></td>
                <td class="operator"><span style="float:left;"><%= t(:from) %> <input type="text" name="date_from" id="date_from" size="10" value="<%= session[:date_from] %>"></span>
                </td>
                <td class="operator">
                  <span style="float:left;"><%= t(:to) %> <input type="text" name="date_to" id="date_to" size="10" value="<%= session[:date_to]%>"></span>
                  <script>
                      $(function() {$( "#date_from" ).datepicker(datepickerOptions);});
                      $(function() {$( "#date_to" ).datepicker(datepickerOptions);});
                  </script>

                </td>
              </tr>
            </table>
          </div>
        </fieldset>
        <fieldset class="collapsible collapsed">
          <legend onclick="toggleFieldset(this);"><%= l(:label_options) %></legend>
          <div style="display: none;">
            <table>
              <tr>
                <td><%= l(:field_column_names) %></td>
                <td><%= render_query_columns_selection(@query) %></td>
              </tr>
              <tr>
                <td><label for='group_by'><%= l(:field_group_by) %></label></td>
                <td><%= select_tag('group_by',
                                   options_for_select(
                                           [[]] + @query.groupable_columns.collect {|c| [c.caption, c.name.to_s]},
                                           @query.group_by)
                        ) %></td>
              </tr>
              <tr>
                <td><%= l(:button_show) %></td>
                <td><%= available_block_columns_tags(@query) %></td>
              </tr>
            </table>
          </div>
        </fieldset>
      </div>
      <p class="buttons">
        <%= link_to_function l(:button_apply), 'submit_query_form("query_form")', :class => 'icon icon-checked' %>
        <%= link_to l(:button_clear), { :set_filter => 1, :project_id => @project }, :class => 'icon icon-reload'  %>
        <% if @query.new_record? && User.current.allowed_to?(:save_queries, @project, :global => true) %>
            <%= link_to_function l(:button_save),
                                 "$('#query_form').attr('action', '#{ @project ? new_project_query_path(@project) : new_query_path }'); submit_query_form('query_form')",
                                 :class => 'icon icon-save' %>
        <% end %>
      </p>
    </div>
<% end %>

app/views/shared/_filters_form.erb
<%= form_tag({ :controller => form_controller, :action => form_action, :project_id => @project },
             :method => :get, :id => 'query_form') do %>
    <div id="query_form_with_buttons" class="hide-when-print">
      <%= hidden_field_tag 'set_filter', '1' %>
      <div id="query_form_content">
        <fieldset id="average_filters" class="collapsible <%= @query.new_record? ? "" : "collapsed" %>">
          <legend onclick="toggleFieldset(this);"><%= t(:label_params_data) %></legend>
          <div style="<%= @query.new_record? ? "" : "display: none;" %>">
            <table style="width: 100%">
              <%= render :partial => input_data %>
            </table>
          </div>
        </fieldset>
        <fieldset id="filters" class="collapsible collapsed">
          <legend onclick="toggleFieldset(this);"><%= l(:label_filter_plural) %></legend>
          <div style="display: none;">
            <%= render :partial => 'queries/filters', :locals => {:query => @query} %>
            <table>
              <tr class="filter" id="tr_dates">
                <td class="field"><input id="cb_dates" name="cb_dates" value="true" type="checkbox" onchange="$(this).val($(this).prop('checked'));" <%= session[:cb_dates] %>><label for="cb_dates"> <%= t(:report_data) %></label></td>
                <td class="operator"><span style="float:left;"><%= t(:from) %> <input type="text" name="date_from" id="date_from" size="10" value="<%= session[:date_from] %>"></span>
                </td>
                <td class="operator">
                  <span style="float:left;"><%= t(:to) %> <input type="text" name="date_to" id="date_to" size="10" value="<%= session[:date_to]%>"></span>
                  <script>
                      $(function() {$( "#date_from" ).datepicker(datepickerOptions);});
                      $(function() {$( "#date_to" ).datepicker(datepickerOptions);});
                  </script>

                </td>
              </tr>
            </table>
          </div>
        </fieldset>
        <fieldset class="collapsible collapsed">
          <legend onclick="toggleFieldset(this);"><%= l(:label_options) %></legend>
          <div style="display: none;">
            <table>
              <tr>
                <td><%= l(:field_column_names) %></td>
                <td><%= render_query_columns_selection(@query) %></td>
              </tr>
              <tr>
                <td><label for='group_by'><%= l(:field_group_by) %></label></td>
                <td><%= select_tag('group_by',
                                   options_for_select(
                                           [[]] + @query.groupable_columns.collect {|c| [c.caption, c.name.to_s]},
                                           @query.group_by)
                        ) %></td>
              </tr>
              <tr>
                <td><%= l(:button_show) %></td>
                <td><%= available_block_columns_tags(@query) %></td>
              </tr>
            </table>
          </div>
        </fieldset>
      </div>
      <p class="buttons">
        <%= link_to_function l(:button_apply), '$("#query_form").submit()', :class => 'icon icon-checked' %>
        <%= link_to l(:button_clear), { :set_filter => 1, :project_id => @project }, :class => 'icon icon-reload'  %>
        <% if @query.new_record? && User.current.allowed_to?(:save_queries, @project, :global => true) %>
            <%= link_to_function l(:button_save),
                                 "$('#query_form').attr('action', '#{ @project ? new_project_query_path(@project) : new_query_path }'); submit_query_form('query_form')",
                                 :class => 'icon icon-save' %>
        <% end %>
      </p>
    </div>
<% end %>

<% if defined? custom_report_partial %>
    <% if custom_report_data.present? %>
        <%= render :partial => custom_report_partial, :locals => { :data => custom_report_data } %>
    <% else %>
        <p class="nodata"><%= t(:no_data) %></p>
    <% end %>
<% else %>
    <%= render :partial => 'shared/optional_diagram', :locals => { :diagram => diagram_partial, :table_data => table_data, :plugin_chart => plugin_chart, :diagram_type => diagram_type } %>
<% end %>

app/views/shared/_not_configure.erb
<div id="errorExplanation"><ul>
  <li><%= t(:error_not_config) %> <a href="/settings/plugin/redmine_report_filters"><%= t(:configure) %></a></li>
</ul></div>

app/views/shared/_optional_diagram.erb
<%= stylesheet_link_tag 'style', :plugin => 'redmine_report_filters' %>
<%= javascript_include_tag 'amcharts.js', :plugin => 'redmine_report_filters' %>
<%= javascript_include_tag plugin_chart, :plugin => 'redmine_report_filters' %>

<% if @table_results.present? && @table_results.count > 0 %>
    <%= render :partial => diagram %>
    <div id="chartdiv" style="width: 100%; min-height: <%= diagram_type == 'pie' && 17 * @chart.split(',').count >= 600  ? 17 * @chart.split(',').count : 600 %>px;"></div>
    <br><br>
    <%= render :partial => table_data, :object => @table_results %>
<% else %>
    <p class="nodata"><%= t(:no_data) %></p>
<% end %>

app/views/shared/_sidebar_menu.erb
<h3 class="template"><%= t(:reports) %></h3>
<%= link_to t(:all_report), project_issues_report_path(@project), :id => 'issue_report' %><br>
<%= link_to t(:average_age_report), project_issues_average_age_report_path(@project), :id => 'average_age_report' %><br>
<%= link_to t(:created_vs_resolved_issues_report), project_issues_created_vs_resolved_report_path(@project), :id => 'created_vs_resolved_issues_report' %><br>
<%= link_to t(:all_projects_closed_vs_resolved_report), project_issues_all_projects_closed_vs_resolved_report_path(@project), :id => 'all_projects_closed_vs_resolved_report' %><br>
<%= link_to t(:pie_chart_report), project_issues_pie_chart_report_path(@project), :id => 'pie_chart_report' %><br>
<%= link_to t(:status_time_report), status_time_report_path(@project), :id => 'status_time_report' %><br>