config/routes.rb
get 'projects/:id/issues/average_age_report', :to => 'project_reports#average_age_report', :as => 'project_issues_average_age_report'
get 'projects/:id/issues/created_vs_resolved_report', :to => 'project_reports#created_vs_resolved_report', :as => 'project_issues_created_vs_resolved_report'
get 'projects/:id/issues/pie_chart_report', :to => 'project_reports#pie_chart_report', :as => 'project_issues_pie_chart_report'
get 'projects/:id/issues/status_time_report', :to => 'project_reports#status_time_report', :as => 'status_time_report'
get 'projects/:id/issues/all_projects_closed_vs_resolved_report', :to => 'project_reports#all_projects_closed_vs_resolved_report', :as => 'project_issues_all_projects_closed_vs_resolved_report'

app/views/reports/_details.html.erb
<script>
    $('.issues').removeClass('selected');
    $('.report').addClass('selected');
</script>
<% if @statuses.empty? or rows.empty? %>
    <p><i><%=l(:label_no_data)%></i></p>
<% else %>
    <table class="list issue-report">
      <thead><tr>
        <th></th>
        <% for status in @statuses %>
            <th><%=h status.name %></th>
        <% end %>
        <th><strong><%=l(:label_open_issues_plural)%></strong></th>
        <th><strong><%=l(:label_closed_issues_plural)%></strong></th>
        <th><strong><%=l(:label_total)%></strong></th>
      </tr></thead>
      <tbody>
      <% if !params[:detail].index('custom_field') %>
          <% for row in rows %>
              <tr class="<%= cycle("odd", "even") %>">
                <td class="name"><%= link_to h(row.name), aggregate_path(@project, field_name, row) %></td>
                <% for status in @statuses %>
                    <td><%= aggregate_link data, { field_name => row.id, "status_id" => status.id }, aggregate_path(@project, field_name, row, :status_id => status.id) %></td>
                <% end %>
                <td><%= aggregate_link data, { field_name => row.id, "closed" => 0 }, aggregate_path(@project, field_name, row, :status_id => "o") %></td>
                <td><%= aggregate_link data, { field_name => row.id, "closed" => 1 }, aggregate_path(@project, field_name, row, :status_id => "c") %></td>
                <td><%= aggregate_link data, { field_name => row.id }, aggregate_path(@project, field_name, row, :status_id => "*") %></td>
              </tr>
          <% end %>
      <% else %>
          <% for row in rows %>
      <%= data %>
              <%
                 rs = CustomValue.joins("INNER JOIN issues ON issues.id = custom_values.customized_id INNER JOIN issue_statuses ON issues.status_id=issue_statuses.id").where(
                         :custom_values => {:custom_field_id => @custom_field.id})
                 if @issues.count != 0 && @query_result_issue.present?
                   rs = rs.where(@query_result_issue)
                   rs = rs.where("(#{Issue.table_name}.created_on >='#{session[:date_from].to_s + " 00:00:00"}' AND #{Issue.table_name}.created_on <='#{session[:date_to].to_s + " 23:59:00"}')") if session[:cb_dates].to_s == "checked"
                 else
                   rs = rs.where("issues.id=0")
                 end
              %>
              <% open = rs.where(:custom_values=>{:value=>row},
                                 :issue_statuses=>{:is_closed => 0}).count %>
              <% close = rs.where(:custom_values=>{:value=>row},
                                  :issue_statuses=>{:is_closed => 1}).count %>
              <% total = close + open
              %>
              <tr class="<%= cycle("odd", "even") %>">
                <td class="name"><%= link_to row, project_issues_path(@project) %></td>
                <% for status in @statuses %>
                    <% pr = rs.where(:custom_values=>{:value=>row},
                                 :issue_statuses=>{:id => status.id}).count %>
                    <td><% if pr != 0 %>
                          <%= link_to pr, project_issues_path(@project) %>
                      <% else %>
                          -
                      <% end %></td>
                <% end %>
                <td><% if open != 0 %>
                      <%= link_to open, project_issues_path(@project) %>
                  <% else %>
                      -
                  <% end %>
                </td>
                <td><% if close != 0 %>
                      <%= link_to close, project_issues_path(@project) %>
                  <% else %>
                      -
                  <% end %></td>
                <td><% if total != 0 %>
                      <%= link_to total, project_issues_path(@project) %>
                  <% else %>
                      -
                  <% end %></td>
              </tr>
          <% end %>
      <% end %>
      </tbody>
    </table>
<% end
   reset_cycle %>

app/views/reports/_simple_subcat.erb
<% if @statuses.empty? or rows.empty? %>
    <p><i><%=l(:label_no_data)%></i></p>
<% else %>
    <table class="list issue-report">
      <thead><tr>
        <th></th>
        <th><%=l(:label_open_issues_plural)%></th>
        <th><%=l(:label_closed_issues_plural)%></th>
        <th><%=l(:label_total)%></th>
      </tr></thead>
      <tbody>
      <% for row in rows %>
          <%
             rs = CustomValue.joins("INNER JOIN issues ON issues.id = custom_values.customized_id INNER JOIN issue_statuses ON issues.status_id=issue_statuses.id").where(
                     :custom_values => {:custom_field_id => custom_field.id })
             if @issues.count != 0 && @query_result_issue.present?
               rs = rs.where(@query_result_issue)
               rs = rs.where("(#{Issue.table_name}.created_on >='#{session[:date_from].to_s + " 00:00:00"}' AND #{Issue.table_name}.created_on <='#{session[:date_to].to_s + " 23:59:00"}')") if session[:cb_dates].to_s == "checked"
             else
               rs = rs.where("issues.id=0")
             end
          %>
          <% open = rs.where(:custom_values=>{:value=>row},
                             :issue_statuses=>{:is_closed => false}).count %>
          <% close = rs.where(:custom_values=>{:value=>row},
                              :issue_statuses=>{:is_closed => true}).count %>
          <% total = close + open
          %>
          <tr class="<%= cycle("odd", "even") %>">
            <td class="name"><%= link_to row, project_issues_path(@project) %></td>
            <td><% if open != 0 %>
                  <%= link_to open, project_issues_path(@project) %>
              <% else %>
              -
              <% end %>
            </td>
            <td><% if close != 0 %>
                  <%= link_to close, project_issues_path(@project) %>
              <% else %>
                  -
              <% end %></td>
            <td><% if total != 0 %>
                  <%= link_to total, project_issues_path(@project) %>
              <% else %>
                  -
              <% end %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
<% end
   reset_cycle %>

app/views/reports/issue_report.html.erb
<script>
    $('.issues').removeClass('selected');
    $('.report').addClass('selected');
    $('#issue_report').css('font-weight', 'bold');
    $('#issue_report').css('color', 'black');
</script>
<h2><%=l(:label_report_plural)%></h2>
<% if @project.enabled_modules.where(:name => 'report_filters').first.present? %>

    <%= javascript_include_tag 'jquery.ui.datepicker.validation.min.js', :plugin => 'redmine_report_filters' %>
    <%= render :partial => 'shared/filters' %>
<% end %>

<div>

</div>

<div class="splitcontentleft">
  <h3><%=l(:field_tracker)%>&nbsp;&nbsp;<%= link_to image_tag('zoom_in.png'), project_issues_report_details_path(@project, :detail => 'tracker') %></h3>
  <%= render :partial => 'simple', :locals => { :data => @issues_by_tracker, :field_name => "tracker_id", :rows => @trackers } %>
  <br />
  <h3><%=l(:field_priority)%>&nbsp;&nbsp;<%= link_to image_tag('zoom_in.png'), project_issues_report_details_path(@project, :detail => 'priority') %></h3>
  <%= render :partial => 'simple', :locals => { :data => @issues_by_priority, :field_name => "priority_id", :rows => @priorities } %>
  <br />
  <h3><%=l(:field_assigned_to)%>&nbsp;&nbsp;<%= link_to image_tag('zoom_in.png'), project_issues_report_details_path(@project, :detail => 'assigned_to') %></h3>
  <%= render :partial => 'simple', :locals => { :data => @issues_by_assigned_to, :field_name => "assigned_to_id", :rows => @assignees } %>
  <br />
  <h3><%=l(:field_author)%>&nbsp;&nbsp;<%= link_to image_tag('zoom_in.png'), project_issues_report_details_path(@project, :detail => 'author') %></h3>
  <%= render :partial => 'simple', :locals => { :data => @issues_by_author, :field_name => "author_id", :rows => @authors } %>
  <br />
  <%= call_hook(:view_reports_issue_report_split_content_left, :project => @project) %>
</div>

<div class="splitcontentright">
  <h3><%=l(:field_version)%>&nbsp;&nbsp;<%= link_to image_tag('zoom_in.png'), project_issues_report_details_path(@project, :detail => 'version') %></h3>
  <%= render :partial => 'simple', :locals => { :data => @issues_by_version, :field_name => "fixed_version_id", :rows => @versions } %>
  <br />
  <% if @project.children.any? %>
      <h3><%=l(:field_subproject)%>&nbsp;&nbsp;<%= link_to image_tag('zoom_in.png'), project_issues_report_details_path(@project, :detail => 'subproject') %></h3>
      <%= render :partial => 'simple', :locals => { :data => @issues_by_subproject, :field_name => "project_id", :rows => @subprojects } %>
      <br />
  <% end %>
  <h3><%=l(:field_category)%>&nbsp;&nbsp;<%= link_to image_tag('zoom_in.png'), project_issues_report_details_path(@project, :detail => 'category') %></h3>
  <%= render :partial => 'simple', :locals => { :data => @issues_by_category, :field_name => "category_id", :rows => @categories } %>
  <br />
  <% @custom_fields.each do |t| %>
      <h3><%= t("#{t.name}") %>&nbsp;&nbsp;<%= link_to image_tag('zoom_in.png'), project_issues_report_details_path(@project, :detail => "custom_field_#{t.id}") %></h3>
      <%= render :partial => 'simple_subcat', :locals => { :custom_field => t, :data => @issues_by_subcategory, :field_name => "custom_field_id", :rows => t.possible_values } %>
      <br />
  <% end %>
  <%= call_hook(:view_reports_issue_report_split_content_right, :project => @project) %>
  <% content_for :sidebar do %>
      <%= render :partial => 'shared/sidebar_menu' %>
  <% end %>
</div>